### ISSUE TITLE
Unable to create an online key registration transaction

### ISSUE THREAD

**Issue by synxero354** [randlabs/algorand-windows-node#1]
Tried the following command to register account online to participate in consensus:

**$ goal account changeonlinestatus -a <account address> -o=1**

But it kept giving me the following error:

**Cannot contact Algorand node: kmd data dir not secure**

**Comment by mxmauro** [comment]
Hi @tankmon354 thanks for the report.

Because Linux and Windows uses a different permission system for directories, we are looking for the best approach to fix this.

Mauro.

**Comment by lazyjeffllc** [comment]
I had the same problem and tried all the solutions suggested for this error when you get it using ssh.
I set owner to my local windows account and removed all other access and even tried setting my access to RWX (instead of full control) then lastly added everyone to deny full control. None of them worked.
Also, I would LOVE some more details about the syntax of the goal account command, I see parameters but not sample values so I don't know where to start. Happy to open a separate note if necessary.

**Comment by hernandp** [comment]
@lazyjeffllc  The Algorand tools rely on checking permissions using the Unix/Linux permission system which does not map 1:1 to Windows native ACLs. 

We are working in a fix for this problem. Thanks for reporting.

**Comment by joshcarpgit** [comment]
Yes, same issue.

**Comment by jonmoshier** [comment]
Any workarounds for this?

**Comment by mxmauro** [comment]
Hi @jonmoshier , actually I'm working on it. But found after doing the initial patches, more things behind were not compatible so taking more time than expected.

**Comment by mxmauro** [comment]
https://github.com/algorand/go-algorand/pull/1942

**Comment by synxero354** [comment]
Hi! Can someone confirm if this has been fixed yet? If so, how will the update be applied to users that have already installed the node? Thanks!

**Comment by hernandp** [comment]
Hello @synxero354, proposed changes already merged in master at Algorand repository.   A new Windows installer will be released once the next stable version is available. Thank you.

**Comment by pao-beep** [comment]
please when will that be? has it already been released? if so i'm still having the same problem; i have stable version 2.5.5 the latest

**Comment by mxmauro** [comment]
Unfortunately the patch has been added to the node repository but releases does not include every commit merged into master. Hope it is added soon

**Comment by pao-beep** [comment]
thank you! what time frame can we expect? and do we have to uninstall and reinstall or just update?

**Comment by pao-beep** [comment]
I see a 2.5.6 has been released, please was this issue fixed in the latest release(2.5.6)?

**Comment by mxmauro** [comment]
Nope. Probably on next release but no date yet.

When you see this file https://github.com/algorand/go-algorand/blob/master/nodecontrol/kmdControl_windows.go in `rel/beta` and `rel/stable` branches, it will be available.

**Comment by mxmauro** [comment]
Hi all, good news.

The new upcoming version 2.6.0 will contain the fix.

**Comment by hernandp** [comment]
I guess we can close this one.
