### ISSUE TITLE
Unable to install prerequisites

### ISSUE THREAD

**Issue by bayuobie** [randlabs/algorand-windows-node#2]
I am trying to install the node for windows but run into problems at step 2. When I try to `./scripts/configure_dev.sh`, I get the error in the picture attached. 
<img width="422" alt="Error" src="https://user-images.githubusercontent.com/4060347/115307768-38adaf00-a159-11eb-9e95-18c9cd65691f.png">

Once I miss this step, all others are failing and I can't get it to work.

**Comment by mxmauro** [comment]
Please follow instructions [here](https://developer.algorand.org/tutorials/compile-and-run-the-algorand-node-natively-windows/)

**Comment by bayuobie** [comment]
I followed the instructions and getting this error at step 2. You can see from picture that I am following the instructions.

**Comment by mxmauro** [comment]
Didn't see the response. You have to use MSYS MingW64 console. Not the MSYS one.
