### ISSUE TITLE
Installer build error because of invalid product version

### ISSUE THREAD

**Issue by ItsSupaMario** [randlabs/algorand-windows-node#3]
![Screenshot 2022-03-04 010921](https://user-images.githubusercontent.com/72972366/156674750-d65eca7c-fb20-4c89-a3bb-7f45a437f5b4.png)
I compiled the binaries from the official Algorand repo and ran into a weird problem while making the installer. The build number seems to mess with the version checking system.

**Comment by hernandp** [comment]
Thanks for your report.    I will check this issue ASAP.

**Comment by hernandp** [comment]
Not reproduced with latest Algorand versions, closing.
