### ISSUE TITLE
No MSI File in te repo

### ISSUE THREAD

**Issue by inazeem** [randlabs/algorand-windows-node#4]
I am unable to locate msi file. Can anyone help me the installation process.

**Comment by hernandp** [comment]
Hello!   The MSI files are generated by running Wix against the installer source.  But you can find MSIs for x64 for both testnet and mainnet installations right here.

https://github.com/randlabs/algorand-windows-node/releases/tag/v3.2.1

**Comment by hernandp** [comment]
@inazeem there is a shiny new release (3.4.2).  Check it here.  Thank you.

https://github.com/randlabs/algorand-windows-node/releases

**Comment by inazeem** [comment]
Thanks for your comment. I have run the node and it is currently running.  But i am not sure where to put the settings and put my wallet address. Is there any requirement to be a node operator? Please help.

**Comment by hernandp** [comment]
@inazeem  You can go to the Start Menu and access Config file settings --
Wallet addresses must be created using goal and kmd.

 You can read Algorand documentation for reference for both topics.
Regards.

**Comment by hernandp** [comment]
This seems to be solved, closing.
