### ISSUE TITLE
Having problems bringing up node using fast catchup with latest release 3.13.2

### ISSUE THREAD

**Issue by makman568** [randlabs/algorand-windows-node#6]
On 2 separate Windows 10 machines (both on the same local network), I have run into an issue where trying to do a fresh install and using fast catchup seems to complete the fast catchup process OK, but the node will not process any new blocks. I see the following error message repeated continuously in node.log:

{"Context":"sync","file":"service.go","function":"github.com/algorand/go-algorand/catchup.(*Service).fetchAndWrite","level":"warning","line":331,"msg":"fetchAndWrite(26652671): lookback block doesn't exist, cannot authenticate new block","name":"","time":"2023-01-31T11:53:58.038642-08:00"

**Comment by hernandp** [comment]
Thanks for your report.

**Comment by hernandp** [comment]
Can you try with the latest release (3.14.2)? Thanks.

**Comment by makman568** [comment]
Looks good! Install went well and node is caught up and running. Thanks.

**Comment by hernandp** [comment]
Glad to hear that.
